### PR TITLE
Typo fixed and tmp path added to indicate that you have to add the path ...

### PR DESCRIPTION
**Pull request by luebbert42**
...to a directory the webserver can write to

:-)

### CODE REVIEW

**Comment by Taluu** [comment]
Hi,

I don't think this is really relevant... but to clarify the example, maybe a fake path like `path/to/excel.xls` shoud be better ? (cuz we do not have to write the excel specifically in the /tmp folder, it could induce people in error just like this case)

**Comment by luebbert42** [comment]
path/to/excel sounds better, yes.

If you don't want to change this (no problem for me), you could add the missing column :-)

**Comment by Taluu** [comment]
You may alter your PR (edit the last commit, new commit, ... whatever), i'm sure @rgazelot is lazy enough to accept this kind of pr rather than doing it himself :D (joke)

**Comment by rgazelot** [comment]
thanks @luebbert42 ;)

**Pull request merged**
